services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Passw0rd

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=Passw0rd
    links:
      - mysql
    ports:
      - 4040:80
    volumes:
      - ./data/phpmyadmin/sessions:/sessions
